### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by nunojesus** [ology/Music#1]
Hi,
I have design this logo for an Algorithm Music project, if you like you can keap it for this project.
If you want it I will give you all the formats of the design free. If you want to make changes please specify.

Greetings

![algo](https://user-images.githubusercontent.com/34600369/39490606-4ddcbbde-4d81-11e8-9972-2315d0e0950a.png)

**Comment by ology** [comment]
Thanks but I don't need a logo for my junk drawer of music experiments. ;-)
